### ISSUE TITLE
Clear button freezes page temporarily

### ISSUE THREAD

**Issue by NicholasDenaro** [Stateware/Dav3i#3]
When pressing the clear button the page freezes. Adding more countries makes the freeze last longer.
There is a noticeable delay with 2 countries. Anything over 5 countries and I was waiting about 10 seconds. I selected 20 countries and after waiting for about a minute, my browser asked me if I wanted to stop the script.
Note: During this time, the whole page is unresponsive!

Steps to reproduce:
Step 1: Open up website.
Step 2: Click a few countries.
Step 3: Click clear

Expected result: Graphs should clear in reasonable time and page should not freeze.
Observed result: Entire page freezes for up to a time at which the browser asks if I want to stop the script.

**Comment by WBittner** [comment]
Freezing occurs on regional and combined, but not whole section(presumably because whole section does not display graphs). Also, this freeze time is significantly shorter for me than Nick, but it still crashed firefox for a half second then it reloaded fine after ~5 seconds of frozen on 10 countries. I have a ton more RAM than nick, but about the same processor speed, so I'm not sure if memory affects our clear time or what, but yeah.

**Comment by WBittner** [comment]
I'm pretty sure this is a related problem, so I'm just posting a comment here, but similarly to clear if you deselect a country after a bunch of countries have been selected, the page freezes up while the deselect is being performed. The more countries, the longer the freeze.

Step 1: Select every country in the Americas.
Step 2: Attempt to deselect the USA.

Expected result: USA turns green and I'm on my way.
Observed result: The page freezes for over 20 seconds, then USA turns green and I'm on my way.

**Comment by jcrafts318** [comment]
This happened as a result of the algorithm used to remove items from the data list when clearing the selection. Because of the unique circumstances of clear the entire selection, it caused the algorithm to run in n^3 time, rather than the normal n^2. This was resolved by simply clearing the list on click of the clear selection button. There is not currently a better way to select or deselect than n^2. We may implement a selection ceiling to avoid large selection sizes.
